version: "3"

networks:
  app-network: null

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: "nginx_blog"
    ports:
      - "8000:80"
    volumes:
      - "./src:/var/www/html"
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    image: "mysql:8"
    container_name: "mysql_blog"
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: vuongnguyen
      MYSQL_PASSWORD: vuongnguyen04040707
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "php_blog"
    user: "${UID:-1000}:${GID:-1000}"
    tty: true
    volumes:
      - "./src:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - app-network

  composer:
    image: "composer"
    container_name: "composer_blog"
    volumes:
      - "./src:/var/www/html"
    working_dir: /var/www/html
    networks:
      - app-network

  npm:
    image: "node:13.7"
    container_name: "npm_blog"
    volumes:
      - "./src:/var/www/html"
    working_dir: /var/www/html
    entrypoint:
      - npm
